### ISSUE TITLE
connection count query isn't always accurate

### ISSUE THREAD

**Issue by douglasAtJoyent** [joyent/pgstatsmon#10]
When there are some active connections, and then suddenly there are not, pgstatsmon is reporting the number of connections that were connected, and not 0.

The test case that I was using to discover this problem is this:
1. Login to the dbserver, though anywhere that you can make a connection to the db and has psql will do. 
2. Create a connection and then put the thread to sleep, I was doing this with select pg_sleep(60); instruction, and ran this through the command line in a for loop backgrounding the process, so I created 105 connections total. I used for i in {1..105}; do nohup sudo -u postgres psql --file=temp.sql& echo $i; done; in bash creating a file named temp.sql with the pg_sleep(60); as the only line. 
3. Wait until the stats are taken, this is defined in the config.
4. Observe the number of connections. For me I was connecting through the default postgres database, so I was using " pg_stat_activity_connections{datacenter="staging-3",datname="postgres",job="pgstatsmon",state="active"} " as my query string in Promethus. At this point I was getting the correct output of 105.
5. Wait again, until all of the connections have disconnected, and a bit more time after that for the stats to be taken again.
6. Observe that the number of connections for the stat in step 4 has not changed.

Expected: This should have gone to 0. 

Note: there was nothing else connecting to this database at the time, which is the cause of the problem. When a new number of active connections is made the stat is correct. e.g. if I connect and run the sleep command again, the number of connections is shown correctly as 1.

**Comment by KodyKantor** [comment]
Thanks for spotting this Douglas!

For future reference, this is due to the way the gauge stats are constructed. pgstatsmon doesn't 'zero out' gauges when it stops observing values from them, so values can hang around in gauges forever. So basically once the connection count for a given 'state' becomes non-zero it will never return to zero with the current code.

We can improve the Postgres query that we run to get connection counts (and possibly other things) to return 'zero' for states that aren't reported.

**Comment by KodyKantor** [comment]
testing notes:
* started pgstatsmon using the vmapi resolver
* checked to make sure pgstatsmon recorded stats for _all_ connection activity, even those that aren't active at all (previously there wouldn't be '0' values reported):
```
$ curl -s localhost:9187/metrics| grep pg_stat_activ | grep cd1cbd | grep moray
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="active",datacenter="walleye"} 1
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="idle",datacenter="walleye"} 17
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="disabled",datacenter="walleye"} 0
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="fastpath function call",datacenter="walleye"} 0
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="idle in transaction",datacenter="walleye"} 0
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="idle in transaction (aborted)",datacenter="walleye"} 0
```
* started an interactive psql shell in the 'moray' database, verified there was an added 'idle' connection (second line went from 17 to 18):
```
$ curl -s localhost:9187/metrics| grep pg_stat_activ | grep cd1cbd | grep moray
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="active",datacenter="walleye"} 1
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="idle",datacenter="walleye"} 18
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="disabled",datacenter="walleye"} 0
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="fastpath function call",datacenter="walleye"} 0
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="idle in transaction",datacenter="walleye"} 0
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="idle in transaction (aborted)",datacenter="walleye"} 0
```
* ran `analyze manta;` and checked that pgstatsmon noticed the change from 'idle' to 'active' (first line incremented, second line decremented):
```
$ curl -s localhost:9187/metrics| grep pg_stat_activ | grep cd1cbd | grep moray
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="active",datacenter="walleye"} 2
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="idle",datacenter="walleye"} 17
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="disabled",datacenter="walleye"} 0
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="fastpath function call",datacenter="walleye"} 0
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="idle in transaction",datacenter="walleye"} 0
pg_stat_activity_connections{backend="3.postgres.walleye.kkantor.com-cd1cbdc3",datname="moray",state="idle in transaction (aborted)",datacenter="walleye"} 0
```

* ran the pgstatsmon tests, which passed:
```
make test
/home/kkantor/manta/pgstatsmon/build/node/bin/node --version
v4.8.7
deps/catest/catest test/*.tst.js
Configuration:
    SRC:                         /home/kkantor/manta/pgstatsmon
    Output directory:            /var/tmp/catest.8271
    Temp directory:              /var/tmp/catest.8271_tmpfiles
    Keep successful test output: false
    Found 2 test(s) to run

===================================================

Executing test test/badquery.tst.js ... success.
Executing test test/basic.tst.js ... success.

===================================================

Results:
	Tests passed:	 2/ 2
	Tests failed:	 0/ 2

===================================================
Cleaning up output from successful tests ... done.
```

**Comment by KodyKantor** [comment]
CR for this change: https://cr.joyent.us/#/c/3936

**Comment by KodyKantor** [comment]
Added in 588149d
